### ISSUE TITLE
Use F_FULLFSYNC on OS X

### ISSUE THREAD

**Issue by untitaker** [untitaker/rust-atomicwrites#13]
https://github.com/untitaker/python-atomicwrites/issues/6

**Comment by untitaker** [comment]
dependent on https://github.com/nix-rust/nix/pull/407

**Comment by probablykasper** [comment]
Judging by [this issue](https://github.com/rust-lang/rust/issues/55920), it seems like `std::sync_all` now uses `F_FULLFSYNC`, which I believe would fix this
