### ISSUE TITLE
`tempdir` has been merged into `tempfile` crate

### ISSUE THREAD

**Issue by Profpatsch** [untitaker/rust-atomicwrites#33]
Since https://github.com/Stebalien/tempfile/commit/328f6485171705af9299b03bf52b5dcc91f7024f (3.0.0), the `tempfile` crate is a superset of `tempdir`.

https://github.com/Stebalien/tempfile/issues/43

**Comment by untitaker** [comment]
@Profpatsch could you make a patch for this?

**Comment by Profpatsch** [comment]
Not in the near future, sadly.

**Comment by asafigan** [comment]
Would this be hard to do? Would you accept a PR for this?

**Comment by untitaker** [comment]
I haven't looked into this at all and I absolutely would accept a PR for this!
