### ISSUE TITLE
Writes are not atomic on Linux

### ISSUE THREAD

**Issue by janderholm** [untitaker/rust-atomicwrites#36]
In order to be atomic on all file systems on Linux the file descriptor of the temporary file must be fsynced before moved. Otherwise data may not have reached disk.

Some file systems sync data before move while others (such as UBIFS) do not:
http://www.linux-mtd.infradead.org/faq/ubifs.html#L_atomic_change

g_file_set_contents is a good source on how to properly write files atomically:
https://github.com/GNOME/glib/blob/1bda4db213bf776143c6d68c4580fd580b1eab5a/glib/gfileutils.c#L1175

**Comment by Profpatsch** [comment]
> In order to be atomic across filesystems on Linux the file descriptor of the temporary file must be fsynced before moved.

Can you even be atomic in that case? I don’t think you can atomically move over filesystem borders.

**Comment by janderholm** [comment]
That was a really bad choice of words on my part. What I really meant by "atomic across filesystems" was "atomic on all different kinds of file systems".

Some file systems make sure that moving a file from A to B makes sure A is first synced to disk. But this is just a nice feature for mitigating a common bug in many implementations and many file systems do not do this. I believe this implementation contain this bug since it doesn't call `tmpfile.sync_all()` before `self.commit() in `AtomicFile::write`, and I can't find any guarantees that a file is synced on drop. It seems the only thing that happens is close is called on the file descriptor.

**Comment by untitaker** [comment]
There are plenty of fixes in python-atomicwrites that have not been ported to this crate. This is one of them.

**Comment by untitaker** [comment]
0.2.5 released
